# cargo-deny configuration


############################################################
# Advisories
############################################################

[advisories]

# RustSec advisory database
db-path = "~/.cargo/advisory-dbs"

# 如果未來需要忽略特定漏洞
ignore = []



############################################################
# Licenses
############################################################

[licenses]

allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0"
]



############################################################
# Bans
############################################################

[bans]

# 同一 crate 多版本
multiple-versions = "warn"

# 禁止 wildcard dependency
wildcards = "deny"



############################################################
# Sources
############################################################

[sources]

unknown-registry = "deny"

unknown-git = "deny"

allow-registry = [
    "https://github.com/rust-lang/crates.io-index"
]